name: reactive_mind_map_example
description: Example app demonstrating the reactive_mind_map package usage.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_mind_map:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 